apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tlc-server.fullname" . }}-config
  labels:
    {{- include "tlc-server.labels" . | nindent 4 }}
data:
  TLC_ENV: "kubernetes"
  MAX_DEPLOYMENTS: {{ .Values.deployments.maxConcurrent | quote }}
  DEPLOYMENTS_NAMESPACE: {{ .Values.deployments.namespace | quote }}
  JWT_EXPIRES_IN: {{ .Values.tlc.jwt.expiresIn | quote }}
