{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tlc-server.fullname" . }}
  labels:
    {{- include "tlc-server.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - dashboard.{{ .Values.domain }}
        - "*.{{ .Values.domain }}"
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    # Dashboard
    - host: dashboard.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "tlc-server.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
    # Wildcard for branch deployments
    - host: "*.{{ .Values.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "tlc-server.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
