apiVersion: v2
name: tlc-server
description: TLC Deployment Server - Test-Led Coding for distributed teams
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - tlc
  - testing
  - ci-cd
  - deployment
  - development
home: https://github.com/jurgencalleja/TLC
sources:
  - https://github.com/jurgencalleja/TLC
maintainers:
  - name: Jurgen Calleja
    url: https://github.com/jurgencalleja
